name = "GregoryLoredo"
uuid = "27cdad02-83ed-4657-a9f5-b5f94b1c509a"
version = "0.1.0"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
CairoMakie = "0.15.6"
ProgressMeter = "1.11.0"
Trapz = "2.0.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
