[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GregoryLoredo = "27cdad02-83ed-4657-a9f5-b5f94b1c509a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ZipStreams = "d1ba5cbe-eaf4-46e4-b1fe-0fd0bb93243b"
